/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveConversation: typeof import('./src/components/chat/ActiveConversation.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ConversationInfo: typeof import('./src/components/chat/ConversationInfo.vue')['default']
    ConversationsMenu: typeof import('./src/components/ConversationsMenu.vue')['default']
    DocumentMessage: typeof import('./src/components/messages/DocumentMessage.vue')['default']
    ImageMessage: typeof import('./src/components/messages/ImageMessage.vue')['default']
    MessageItem: typeof import('./src/components/messages/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMessage: typeof import('./src/components/chat/SendMessage.vue')['default']
    VideoMessage: typeof import('./src/components/messages/VideoMessage.vue')['default']
  }
}
